version: '2'

services:
  camera:
    build: ./
    environment:
      - SELENIUM_BROWSER=chrome
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    ports:
      - "3000:3000"
  selenium:
    image: selenium/standalone-chrome:3.0.1-aluminum
    expose:
      - "4444"
    volumes:
      # Workaround for Chrome:
      # https://code.google.com/p/chromium/issues/detail?id=519952
      - /dev/shm:/dev/shm
